/*
 * generated by Xtext 2.12.0
 */
package de.seronet_projekt.ros.interfaces.pool


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RosInterfacesPoolRuntimeModule extends AbstractRosInterfacesPoolRuntimeModule {
}
