/**
 */
package rosInterfacesPool.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import rosInterfacesPool.util.RosInterfacesPoolAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class RosInterfacesPoolItemProviderAdapterFactory extends RosInterfacesPoolAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RosInterfacesPoolItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link rosInterfacesPool.RosInterfacesPool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RosInterfacesPoolItemProvider rosInterfacesPoolItemProvider;

	/**
	 * This creates an adapter for a {@link rosInterfacesPool.RosInterfacesPool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRosInterfacesPoolAdapter() {
		if (rosInterfacesPoolItemProvider == null) {
			rosInterfacesPoolItemProvider = new RosInterfacesPoolItemProvider(this);
		}

		return rosInterfacesPoolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rosInterfacesPool.RosPublisher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RosPublisherItemProvider rosPublisherItemProvider;

	/**
	 * This creates an adapter for a {@link rosInterfacesPool.RosPublisher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRosPublisherAdapter() {
		if (rosPublisherItemProvider == null) {
			rosPublisherItemProvider = new RosPublisherItemProvider(this);
		}

		return rosPublisherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rosInterfacesPool.RosSubscriber} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RosSubscriberItemProvider rosSubscriberItemProvider;

	/**
	 * This creates an adapter for a {@link rosInterfacesPool.RosSubscriber}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRosSubscriberAdapter() {
		if (rosSubscriberItemProvider == null) {
			rosSubscriberItemProvider = new RosSubscriberItemProvider(this);
		}

		return rosSubscriberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rosInterfacesPool.RosSrvServer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RosSrvServerItemProvider rosSrvServerItemProvider;

	/**
	 * This creates an adapter for a {@link rosInterfacesPool.RosSrvServer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRosSrvServerAdapter() {
		if (rosSrvServerItemProvider == null) {
			rosSrvServerItemProvider = new RosSrvServerItemProvider(this);
		}

		return rosSrvServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rosInterfacesPool.RosSrvClient} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RosSrvClientItemProvider rosSrvClientItemProvider;

	/**
	 * This creates an adapter for a {@link rosInterfacesPool.RosSrvClient}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRosSrvClientAdapter() {
		if (rosSrvClientItemProvider == null) {
			rosSrvClientItemProvider = new RosSrvClientItemProvider(this);
		}

		return rosSrvClientItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rosInterfacesPool.RosActionServer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RosActionServerItemProvider rosActionServerItemProvider;

	/**
	 * This creates an adapter for a {@link rosInterfacesPool.RosActionServer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRosActionServerAdapter() {
		if (rosActionServerItemProvider == null) {
			rosActionServerItemProvider = new RosActionServerItemProvider(this);
		}

		return rosActionServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rosInterfacesPool.RosActionClient} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RosActionClientItemProvider rosActionClientItemProvider;

	/**
	 * This creates an adapter for a {@link rosInterfacesPool.RosActionClient}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRosActionClientAdapter() {
		if (rosActionClientItemProvider == null) {
			rosActionClientItemProvider = new RosActionClientItemProvider(this);
		}

		return rosActionClientItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (rosInterfacesPoolItemProvider != null) rosInterfacesPoolItemProvider.dispose();
		if (rosPublisherItemProvider != null) rosPublisherItemProvider.dispose();
		if (rosSubscriberItemProvider != null) rosSubscriberItemProvider.dispose();
		if (rosSrvServerItemProvider != null) rosSrvServerItemProvider.dispose();
		if (rosSrvClientItemProvider != null) rosSrvClientItemProvider.dispose();
		if (rosActionServerItemProvider != null) rosActionServerItemProvider.dispose();
		if (rosActionClientItemProvider != null) rosActionClientItemProvider.dispose();
	}

}
