<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rosInterfacesPool" nsURI="http://www.seronet-projekt.de/rosInterfacesPool"
    nsPrefix="rosInterfacesPool">
  <eClassifiers xsi:type="ecore:EClass" name="RosInterfacesPool">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//RosInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosTopic" abstract="true" eSuperTypes="#//RosInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topicName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosService" abstract="true" eSuperTypes="#//RosInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srvName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosPublisher" eSuperTypes="#//RosTopic"/>
  <eClassifiers xsi:type="ecore:EClass" name="RosSubscriber" eSuperTypes="#//RosTopic"/>
  <eClassifiers xsi:type="ecore:EClass" name="RosSrvServer" eSuperTypes="#//RosService"/>
  <eClassifiers xsi:type="ecore:EClass" name="RosSrvClient" eSuperTypes="#//RosService"/>
  <eClassifiers xsi:type="ecore:EClass" name="RosInterface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosActionServer" eSuperTypes="#//RosAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="RosActionClient" eSuperTypes="#//RosAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="RosAction" abstract="true" eSuperTypes="#//RosInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
