<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rosPortExtension" nsURI="http://www.seronet-projekt.de/component/rosPortExtension"
    nsPrefix="rosPortExtension">
  <eClassifiers xsi:type="ecore:EClass" name="ExtendsComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//ComponentDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//RosPortSelection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosPortSelection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../de.seronet_projekt.ros.interfaces.pool/model/rosInterfacesPool.ecore#//RosInterface"/>
  </eClassifiers>
</ecore:EPackage>
