/*
 * generated by Xtext 2.16.0
 */
package de.seronet_projekt.ros.interfaces.pool.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RosInterfacesPoolAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/seronet_projekt/ros/interfaces/pool/parser/antlr/internal/InternalRosInterfacesPool.tokens");
	}
}
